### CONSTANTS ###
SCREEN_WIDHT = 800
SCREEN_HEIGHT = 600
INFO_BAR_HEIGHT = 30
GAME_AREA_HEIGHT = SCREEN_HEIGHT - INFO_BAR_HEIGHT

BLOCK_WIDTH = 50
BLOCK_HEIGHT = 30

PLAYER_FRAME_DIM = 115

AMBLER_GOBLIN_FRAME_DIM = 45

BLOOD_BALL_FRAME_DIM = 50

HORIZONTAL_DIRECTION = 1
VERTICAL_DIRECTION = 2